### ISSUE TITLE
What to change to remove info from: from_chat_id

### ISSUE THREAD

**Issue by enthousiast** [tgMember/tdAds#3]
hello @sajjad-021 

is there maybe please any way that i can disable this function: from_chat_id

i want to forward messages but it keep showing the "Forwarded From" text when i forward a message from one channel to my channel

please let me know, i am searching for more then a week now and i can not find it anywhere

thank you very much

**Comment by enthousiast** [comment]
i just found the getchannel function and i think i need to edit this part but the code from telegram-bot is fully encrypted

do you think i need to change this code somehow?

https://github.com/rizaumami/tdbot.lua/wiki/getChannel

i think i need to set "sign messages" to false but i am not sure how that would be possible?

sorry to bother you so much, hope you can help me!

thanks for million times!

**Comment by sajjad-021** [comment]
Hi dear friend
for to send messages from other channel to your channel as usual without forwarding, you need to change the 861 line.
"forwardMessages" change to "sendMessage"

**Comment by enthousiast** [comment]
thank you so much for all your help bro, this is the most friendly guy i ever met on the internet
