### ISSUE TITLE
no server running

### ISSUE THREAD

**Issue by sla-te** [tgMember/tdAds#4]
no server running on /tmp/tmux-1000/default
[exited]

and what is the user-id?

**Comment by sajjad-021** [comment]
- ## tmux error
1- use ubuntu 18 x64 os
2- besure run on root access
_then_
**follow command:**
```rm -rf ~/.telegram-bot; apt list --upgradable -a; apt update -y; apt upgrade -y; apt install --reinstall tmux screen -y; dpkg --configure -a; apt --fix-broken install -y; apt-get -f install; sync; apt autoclean; apt autoremove -y; apt update -y; apt full-upgrade -y;  cd ~/tdAds; bash TD upgrade```
now you must restart your system by below command:
```reboot```
after loading system try again to launch robot.

- ## user id
for find account user-id you can using:
[@userinfobot](https://t.me/userinfobot)
It is usually a 8, 9 or 10 digit number.
